- name: Установка Zabbix сервера
  hosts: zabbix
  become: true

  tasks:
    - name: Установка зависимостей
      apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - mariadb-server
        state: present
        update_cache: true

    - name: Убедиться, что MariaDB работает
      service:
        name: mariadb
        state: started
        enabled: true

    - name: Убедиться, что Zabbix сервер работает
      service:
        name: zabbix-server
        state: started
        enabled: true
