- name: Установка Zabbix Agent
  hosts: all
  become: true

  tasks:
    - name: Установка пакета Zabbix Agent
      apt:
        name: zabbix-agent
        state: present
        update_cache: true

    - name: Копирование конфигурации Zabbix Agent
      template:
        src: templates/zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
        mode: "0644"
      notify: Перезапуск агента

  handlers:
    - name: Перезапуск агента
      service:
        name: zabbix-agent
        state: restarted
