---
- name: Install Zabbix Agent on all VMs
  hosts: all
  become: true

  vars:
    zabbix_server_ip: "{{ hostvars['zabbix-server']['ansible_host'] | default('192.168.10.32') }}"

  tasks:
    - name: Install Zabbix repo
      apt:
        deb: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Zabbix Agent
      apt:
        name: zabbix-agent
        state: present

    - name: Deploy agent config
      template:
        src: templates/zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
        mode: 0644

    - name: Enable and start agent
      service:
        name: zabbix-agent
        enabled: true
        state: started
